sudo: required

services:
  - docker

language: go

go: 1.7.x

install:
  - go get github.com/openshift/source-to-image
  - pushd ${GOPATH}/src/github.com/openshift/source-to-image
  - export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
  - hack/install-tools.sh
  - hack/build-go.sh
  - popd

script:
  - make
  - s2i build https://github.com/edewit/minecraft-sample-plugin.git edewit/minecraft-sponge-plugin-s2i minecraft-sample-plugin
