sudo: required

services:
  - docker

language: go

go: 1.6

install:
  - export GOPATH=`pwd`
  - go get github.com/openshift/source-to-image
  - pushd ${GOPATH}/src/github.com/openshift/source-to-image
  - export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
  - hack/build-go.sh
  - popd

script:
  - make
  - s2i build git@github.com:edewit/minecraft-sample-plugin.git edewit/minecraft-plugin-centos minecraft-sample-plugin
